from single_pokemon import SinglePokemon

ditto = SinglePokemon("ditto")

#print(ditto.response_data().abilities)
print(ditto.response_data().ability1)
print(ditto.response_data().ability2)
print(ditto.response_data().base_experience)
print(ditto.response_data().formname)
print(ditto.response_data().formurl)
print(ditto.response_data().game_1_details)
print(ditto.response_data().game_2_details)
print(ditto.response_data().game_3_details)
print(ditto.response_data().game_4_details)
print(ditto.response_data().game_5_details)
print(ditto.response_data().game_6_details)
print(ditto.response_data().game_7_details)
print(ditto.response_data().game_8_details)
print(ditto.response_data().game_9_details)
print(ditto.response_data().game_10_details)
print(ditto.response_data().game_11_details)
print(ditto.response_data().game_12_details)
print(ditto.response_data().game_13_details)
print(ditto.response_data().game_14_details)
print(ditto.response_data().game_15_details)
print(ditto.response_data().game_16_details)
print(ditto.response_data().game_17_details)
print(ditto.response_data().game_18_details)
print(ditto.response_data().game_19_details)
print(ditto.response_data().game_20_details)
print(ditto.response_data().weight)
print(ditto.response_data().id)
print(ditto.response_data().is_default)
print(ditto.response_data().loc_encounter)
print(ditto.response_data().height)